In [45]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import random_split, TensorDataset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [30]:
df = pd.read_csv('fetal_health.csv')

In [31]:
df.head()

baseline value  accelerations  fetal_movement  uterine_contractions   
0           120.0          0.000             0.0                 0.000  \
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations   
0                0.000                   0.0                       0.0  \
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability   
0                             73.0                                   0.5  \
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min   
0                                               43.0       ...           62.0  \
1                                                0.0       ...           68.0   
2                                                0.0       ...           68.0   
3                                                0.0       ...           53.0   
4                                                0.0       ...           53.0   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes   
0          126.0                        2.0                         0.0  \
1          198.0                        6.0                         1.0   
2          198.0                        5.0                         1.0   
3          170.0                       11.0                         0.0   
4          170.0                        9.0                         0.0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance   
0           120.0           137.0             121.0                73.0  \
1           141.0           136.0             140.0                12.0   
2           141.0           135.0             138.0                13.0   
3           137.0           134.0             137.0                13.0   
4           137.0           136.0             138.0                11.0   

   histogram_tendency  fetal_health  
0                 1.0           2.0  
1                 0.0           1.0  
2                 0.0           1.0  
3                 1.0           1.0  
4                 1.0           1.0  

[5 rows x 22 columns]

In [32]:
datos_y = df[df.columns[-1]]
datos_y.head()

0    2.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: fetal_health, dtype: float64

In [33]:
datos_x = df.drop(columns=["fetal_health"])
datos_x.head()

baseline value  accelerations  fetal_movement  uterine_contractions   
0           120.0          0.000             0.0                 0.000  \
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations   
0                0.000                   0.0                       0.0  \
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability   
0                             73.0                                   0.5  \
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...   
0                                               43.0       ...  \
1                                                0.0       ...   
2                                                0.0       ...   
3                                                0.0       ...   
4                                                0.0       ...   

   histogram_width  histogram_min  histogram_max  histogram_number_of_peaks   
0             64.0           62.0          126.0                        2.0  \
1            130.0           68.0          198.0                        6.0   
2            130.0           68.0          198.0                        5.0   
3            117.0           53.0          170.0                       11.0   
4            117.0           53.0          170.0                        9.0   

   histogram_number_of_zeroes  histogram_mode  histogram_mean   
0                         0.0           120.0           137.0  \
1                         1.0           141.0           136.0   
2                         1.0           141.0           135.0   
3                         0.0           137.0           134.0   
4                         0.0           137.0           136.0   

   histogram_median  histogram_variance  histogram_tendency  
0             121.0                73.0                 1.0  
1             140.0                12.0                 0.0  
2             138.0                13.0                 0.0  
3             137.0                13.0                 1.0  
4             138.0                11.0                 1.0  

[5 rows x 21 columns]

In [34]:
datos_x = pd.get_dummies(datos_x)
datos_x.head()

baseline value  accelerations  fetal_movement  uterine_contractions   
0           120.0          0.000             0.0                 0.000  \
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations   
0                0.000                   0.0                       0.0  \
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability   
0                             73.0                                   0.5  \
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...   
0                                               43.0       ...  \
1                                                0.0       ...   
2                                                0.0       ...   
3                                                0.0       ...   
4                                                0.0       ...   

   histogram_width  histogram_min  histogram_max  histogram_number_of_peaks   
0             64.0           62.0          126.0                        2.0  \
1            130.0           68.0          198.0                        6.0   
2            130.0           68.0          198.0                        5.0   
3            117.0           53.0          170.0                       11.0   
4            117.0           53.0          170.0                        9.0   

   histogram_number_of_zeroes  histogram_mode  histogram_mean   
0                         0.0           120.0           137.0  \
1                         1.0           141.0           136.0   
2                         1.0           141.0           135.0   
3                         0.0           137.0           134.0   
4                         0.0           137.0           136.0   

   histogram_median  histogram_variance  histogram_tendency  
0             121.0                73.0                 1.0  
1             140.0                12.0                 0.0  
2             138.0                13.0                 0.0  
3             137.0                13.0                 1.0  
4             138.0                11.0                 1.0  

[5 rows x 21 columns]

In [35]:
escalador = StandardScaler()
datos_x = escalador.fit_transform(datos_x)
print(datos_x)

[[-1.35222005 -0.8223883  -0.20320955 ... -1.18164215  1.87056871
   1.11298001]
 [-0.1325256   0.73013282 -0.20320955 ...  0.13203796 -0.23499819
  -0.52452553]
 [-0.03088439 -0.04612774 -0.20320955 ... -0.00624416 -0.2004807
  -0.52452553]
 ...
 [ 0.68060404 -0.56363478 -0.20320955 ...  0.96173066 -0.51113811
   1.11298001]
 [ 0.68060404 -0.56363478 -0.20320955 ...  0.8925896  -0.51113811
   1.11298001]
 [ 0.88388645 -0.30488126 -0.16034157 ...  0.47774325 -0.61469058
  -0.52452553]]


In [36]:
datos_x.shape[0]

2126

In [37]:
train_x, test_x, train_y, test_y = train_test_split(datos_x, datos_y, test_size=0.2, random_state=2)

In [38]:
n_entradas = train_x.shape[1]

In [39]:
t_train_x = torch.from_numpy(train_x).float().to("cpu")
t_test_x = torch.from_numpy(test_x).float().to("cpu")
t_train_y = torch.from_numpy(train_y.values).float().to("cpu")
t_test_y = torch.from_numpy(test_y.values).float().to("cpu")
t_train_y = t_train_y[:, None]
t_test_y = t_test_y[:, None]

In [40]:
test = TensorDataset(t_test_x, t_test_y)
print(test[0])

(tensor([ 1.4937e+00, -8.2239e-01, -2.0321e-01,  2.1511e-01, -6.3844e-01,
        -5.7476e-02, -2.6875e-01,  1.1693e-01, -8.2985e-01, -4.8099e-01,
         2.5100e-01, -1.2696e+00,  1.6723e+00, -1.4158e-03, -1.3797e+00,
        -4.5844e-01,  1.0715e+00,  1.2437e+00,  1.2383e+00, -6.4921e-01,
        -5.2453e-01]), tensor([1.]))


In [41]:
t_train_y

tensor([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]])

In [42]:
class Red(nn.Module):
    def __init__(self, n_entradas):
        super(Red, self).__init__()
        self.linear1 = nn.Linear(n_entradas, 15)
        self.linear2 = nn.Linear(15, 8)
        self.linear3 = nn.Linear(8, 1)

    def forward(self, inputs):
        pred_1 = torch.sigmoid(input=self.linear1(inputs))
        pred_2 = torch.sigmoid(input=self.linear2(pred_1))
        pred_f = torch.sigmoid(input=self.linear3(pred_2))
        return pred_f

In [44]:
%%time

lr = 0.001
epochs = 2000
status_print = 100

model = Red(n_entradas=n_entradas)
loss_fn = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
print("Arquitectura del modelo: {}".format(model))
historic = pd.DataFrame()

print("Entrenamiento del modelo")
for epoch in range(1, epochs+1):
    y_pred = model(t_train_x)
    loss = loss_fn(input=y_pred, target=t_train_y)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    if epoch % status_print == 0:
        print(f"\nEpoch {epoch} \t Loss: {round(loss.item(), 4)}")

    with torch.no_grad():
        y_pred = model(t_test_x)
        y_pred_class = y_pred.round()
        correct = (y_pred_class == t_test_y).sum()
        accuracy = 100 * correct / float(len(t_test_y))
        if epoch % status_print == 0:
            print("Accuracy: {}".format(accuracy.item()))

    df_tmp = pd.DataFrame(data={
    "Epoch": [epoch],
    "Loss": [loss.item()],
    "Accuracy": [round(accuracy.item(), 4)]
    })
    historic = pd.concat(objs=[historic, df_tmp])
    
print("Accuracy final: {}".format(round(accuracy.item(), 4)))

Arquitectura del modelo: Red(
  (linear1): Linear(in_features=21, out_features=15, bias=True)
  (linear2): Linear(in_features=15, out_features=8, bias=True)
  (linear3): Linear(in_features=8, out_features=1, bias=True)
)
Entrenamiento del modelo



Epoch 100 	 Loss: 0.0478
Accuracy: 80.28169250488281

Epoch 200 	 Loss: -0.3732
Accuracy: 80.28169250488281

Epoch 300 	 Loss: -0.6981
Accuracy: 80.28169250488281

Epoch 400 	 Loss: -0.9557
Accuracy: 80.28169250488281

Epoch 500 	 Loss: -1.1929
Accuracy: 80.28169250488281

Epoch 600 	 Loss: -1.4556
Accuracy: 80.28169250488281

Epoch 700 	 Loss: -1.7082
Accuracy: 80.28169250488281

Epoch 800 	 Loss: -1.9514
Accuracy: 80.28169250488281

Epoch 900 	 Loss: -2.1912
Accuracy: 80.28169250488281

Epoch 1000 	 Loss: -2.4303
Accuracy: 80.28169250488281

Epoch 1100 	 Loss: -2.6705
Accuracy: 80.28169250488281

Epoch 1200 	 Loss: -2.9167
Accuracy: 80.28169250488281

Epoch 1300 	 Loss: -3.2298
Accuracy: 80.28169250488281

Epoch 1400 	 Loss: -3.56
Accuracy: 80.28169250488281

Epoch 1500 	 Loss: -3.8656
Accuracy: 80.28169250488281

Epoch 1600 	 Loss: -4.1699
Accuracy: 80.28169250488281

Epoch 1700 	 Loss: -4.4366
Accuracy: 80.28169250488281

Epoch 1800 	 Loss: -4.7811
Accuracy: 80.28169250488281

Epo

In [49]:
t_test_x[5]

tensor([ 0.0708, -0.8224, -0.2032,  0.8941,  1.7268, -0.0575, -0.2688, -1.5702,
         0.9821, -0.3723,  1.2284,  1.0926, -1.4746, -0.0572,  0.9943,  0.9582,
        -0.6993, -0.9372, -0.7668,  1.1112,  1.1130])

In [55]:
classification = model(t_test_x[5])
print(classification)

tensor([0.5818], grad_fn=<SigmoidBackward0>)


In [52]:
t_test_y[5]

tensor([1.])